### ISSUE TITLE
Handle shell escape sequences for colors and font style

### ISSUE THREAD

**Issue by katyukha** [nonanonno/tabletool#1]
Hi,

Thanks for nice package)

I have spotted bug relate to colored output in shell, currently module computes width for bash escape sequences.

Just take a look at screenshots below:

Without colors:
![image](https://github.com/nonanonno/tabletool/assets/1129820/9f6892bd-ab40-4c12-9a38-955f9ecc53c3)

With colors:
![image](https://github.com/nonanonno/tabletool/assets/1129820/453ab0ea-8b6a-4b8d-8b3d-3e44dea19095)

Thanks)

**Comment by nonanonno** [comment]
@katyukha 
Hi.

Thank you for your report! I believe it's fixed in v0.4.0. This is the screen shot in my environment.

<img width="236" alt="Screenshot 2023-05-17 at 0 42 24" src="https://github.com/nonanonno/tabletool/assets/10045065/a8e118bf-89fc-449f-808c-d92af59f151c">

**Comment by katyukha** [comment]
Thanks a lot)

I just have tested main branch, and now it seems to be working)

Thanks)
